#ifndef DBUDDY_STYLES_H
#define DBUDDY_STYLES_H

#include "lvgl/lvgl.h"

#define DEFAULT_PADDING 12
#define DEFAULT_BORDER 5
#define DEFAULT_MENU_HEIGHT 24
#define DEFAULT_LIST_WIDTH 160

extern lv_style_t style_default_background_blend_mode_additive;
extern lv_style_t style_default_background_blend_mode_subtractive;
extern lv_style_t style_default_background_color_black;
extern lv_style_t style_default_background_color_blue;
extern lv_style_t style_default_background_overlay_color_black;
extern lv_style_t style_default_background_transparent_10;
extern lv_style_t style_default_background_transparent_20;
extern lv_style_t style_default_background_transparent_30;
extern lv_style_t style_default_background_transparent_40;
extern lv_style_t style_default_background_transparent_60;
extern lv_style_t style_default_background_transparent_70;
extern lv_style_t style_default_background_transparent_80;
extern lv_style_t style_default_background_transparent_90;
extern lv_style_t style_default_background_transparent_cover;
extern lv_style_t style_default_background_transparent_full;
extern lv_style_t style_default_background_transparent_half;
extern lv_style_t style_default_border_color_white;
extern lv_style_t style_default_border_none;
extern lv_style_t style_default_border_sides_only_bottom;
extern lv_style_t style_default_border_sides_only_right;
extern lv_style_t style_default_border_sides_right_none;
extern lv_style_t style_default_border_thin;
extern lv_style_t style_default_font_black_large;
extern lv_style_t style_default_font_black_large_48;
extern lv_style_t style_default_font_black_large_72;
extern lv_style_t style_default_font_black_medium;
extern lv_style_t style_default_font_black_small;
extern lv_style_t style_default_font_regular_large;
extern lv_style_t style_default_font_regular_large_48;
extern lv_style_t style_default_font_regular_large_72;
extern lv_style_t style_default_font_regular_medium;
extern lv_style_t style_default_font_regular_small;
extern lv_style_t style_default_margin_none;
extern lv_style_t style_default_padding_default;
extern lv_style_t style_default_padding_top_none;
extern lv_style_t style_default_padding_left_none;
extern lv_style_t style_default_padding_right_none;
extern lv_style_t style_default_padding_bottom_none;
extern lv_style_t style_default_padding_none;
extern lv_style_t style_default_radius_none;
extern lv_style_t style_default_radius_normal;
extern lv_style_t style_default_shadow_none;
extern lv_style_t style_default_text_color_black;
extern lv_style_t style_focused_border_color_white;

extern lv_style_t style_focused_background_blend_mode_additive;
extern lv_style_t style_focused_background_blend_mode_subtractive;
extern lv_style_t style_focused_background_color_purple;
extern lv_style_t style_focused_border_none;
extern lv_style_t style_focused_border_sides_only_right;
extern lv_style_t style_focused_border_thin;
extern lv_style_t style_focused_text_color_black;

extern lv_style_t style_pressed_background_color_none;

void styles_init(void);

#endif //DBUDDY_STYLES_H
